---
title: "Covid map of Italy"
author: "Saja"
output: 
  html_document:
    keep_md: true
---
```{r include=FALSE}
# some global options
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_knit$set(cache = TRUE)
knitr::opts_chunk$set(fig.path = "./figure/")
knitr::opts_chunk$set(fig.align = "center")

repo_url <- "https://github.com/pcm-dpc/COVID-19"
```


## Introduction
This is a demo document to create a map of counts of cvoid patients in Italy, using leaflet.


```{r }
library("tidyverse")
library("leaflet")
```

### Getting the data

For this demo I'll be using this [github][1] repository.

```{r echo=FALSE}
if (!(dir.exists("./data"))) {
    dir.create("./data/")
    download.file(
        # url = paste(repo_url, "/blob/master/", "dati-regioni/", "dpc-covid19-ita-regioni.csv", sep = "/"),
        url = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni-latest.csv",
        destfile = "./data/latest.csv", overwrite = TRUE
    )
}
if (!(dir.exists("./COVID-19/"))) {
    system(paste(
        "git", "clone",
        repo_url,
        sep = " "
    ))
} else {
    setwd("COVID-19")
    system(paste(
        "git", "pull",
        "origin", "master",
        sep = " "
    ))
    setwd("../")
}
```

Now lets read the data.

```{r loadData}
df <- read_csv("./data/latest.csv")
df <- df %>%
    select(c("denominazione_regione", "lat", "long", "totale_casi"))


names(df) <- c("name", "latitude", "longitude", "cases")
head(df)
```

Now I'm going to draw a map of italy with total number of new cases in each region of italy.

```{r plot}
df %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 1, radius = df$cases / 100, color = "red", popup = df$name)
```
This data generated on: `r date()`

[1]: `r repo_url` "Health Ministery"